apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: v1
kind: Pod
metadata:
  name: title
  labels:
    role: title
spec:
  containers:
    - name: title
      image: ubuntu:24.04
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
